-- 코드를 입력하세요
# SELECT t1.TITLE, t1.BOARD_ID, t2.REPLY_ID, t2.WRITER_ID, t2.CONTENTS, DATE_FORMAT(t2.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
# FROM USED_GOODS_BOARD t1
# left join USED_GOODS_REPLY t2
# on t1.BOARD_ID = t2.BOARD_ID 
# WHERE DATE_FORMAT(t2.CREATED_DATE,'%Y-%m') = '2022-10'
# order by t2.CREATED_DATE , t1.TITLE;

SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY B.CREATED_DATE, A.TITLE;